# Generated by Django 5.1.5 on 2025-01-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
